package com.redsocial.media;

import java.nio.file.Path;

/** External object storage boundary. Keys are generated by the application. */
public interface MediaStorage {
    void upload(String key, Path file, String contentType);

    void delete(String key);
}
