export const chatCopy = {
  title: "Mensajes privados",
  intro: "Conversa en tiempo real con tus compañeros.",
  conversations: "Conversaciones",
  emptyList: "Todavía no tienes conversaciones.",
  emptyListHelp: "Visita el perfil de un compañero para iniciar un chat.",
  selectConversation: "Elige una conversación para ver los mensajes.",
  emptyHistory: "Esta conversación todavía no tiene mensajes.",
  older: "Cargar mensajes anteriores",
  loadingOlder: "Cargando mensajes…",
  draft: "Escribe un mensaje",
  send: "Enviar mensaje",
  connecting: "Conectando…",
  connected: "Conectado",
  reconnecting: "Conexión interrumpida. Reconectando…",
  sendUnavailable: "Espera a que el chat se conecte para enviar mensajes.",
  sendError: "No pudimos enviar el mensaje. Inténtalo de nuevo.",
  historyError: "No pudimos cargar los mensajes.",
  conversationsError: "No pudimos cargar tus conversaciones.",
  startError: "No pudimos iniciar la conversación. Inténtalo de nuevo.",
  start: "Enviar mensaje",
  back: "Volver a conversaciones",
  backShort: "Volver",
  messageFrom: (name: string) => "Mensaje de " + name,
} as const;
